<a href="https://colab.research.google.com/github/mohamedhossam23/Python/blob/main/Numby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

إنشاء مصفوفات NumPy


In [2]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

2-D المصفوفات

In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

3-D المصفوفات


In [5]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

عدد أبعاد المصفوفة

In [6]:
arr3.ndim

3

مصفوفات ذات أبعاد أعلى


In [7]:
import numpy as np

arr4 = np.array([1, 2, 3, 4], ndmin=5)
arr4

array([[[[[1, 2, 3, 4]]]]])

In [8]:
arr4.ndim

5

دمج إلى المصفوفات (Joining)


In [10]:
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])
mixed_arr = np.concatenate((arr5, arr6))
mixed_arr

array([1, 2, 3, 4, 5, 6])

تقسيم المصفوفات

In [12]:
sparr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(sparr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

البحث في المصفوفات

In [13]:
searcharr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(searcharr == 4)
x

(array([3, 5, 6]),)

فرز المصفوفات

In [15]:
sortarr = np.array([3, 2, 0, 1])
np.sort(sortarr)

[0 1 2 3]


فرز مجموعة ثنائية الأبعاد

In [17]:
sortarr2 = np.array([[3, 2, 4], [5, 0, 1]])
np.sort(sortarr2)

array([[2, 3, 4],
       [0, 1, 5]])

تصفية المصفوفة

In [20]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

newarr

array([43, 44])